export ZDOTDIR=$HOME/.config/zsh

export PATH=$HOME/.local/bin:$PATH
export LESS="-giMQR -j3 --incsearch"
export EDITOR=nvim
export BROWSER=firefox

# theme
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_STYLE_OVERRIDE=kvantum
