#!/usr/bin/env bash

STATE_DIR="$HOME/.local/state/privacy-desktop"
mkdir -p $STATE_DIR
STATE_FILE="$STATE_DIR/enabled"
MUTE_FILE="$STATE_DIR/muted"

current_state=${1:-$(cat "$STATE_FILE" 2> /dev/null || echo 0)}

if [[ "$current_state" == 0 ]]; then
    if wpctl get-volume @DEFAULT_SINK@ | grep -q 'MUTED'; then
        echo 1 > "$MUTE_FILE"
    else
        wpctl set-mute @DEFAULT_SINK@ 1
    fi
    echo 1 > "$STATE_FILE"
    hyprctl dispatch workspace name:D
else
    if [[ -f "$MUTE_FILE" ]] && [[ $(cat "$MUTE_FILE") == 1 ]]; then
        rm "$MUTE_FILE"
    else
        wpctl set-mute @DEFAULT_SINK@ 0
    fi
    echo 0 > "$STATE_FILE"
    hyprctl dispatch workspace previous
fi
