# Zsh

export ZDOTDIR=$HOME/.config/zsh
export ZCONFIGDIR=$ZDOTDIR/config


# Common

export PATH=$HOME/.local/bin:$PATH
export LESS="-giMQR -j3 --incsearch"
export EDITOR=nvim
export BROWSER=firefox
export TERMINAL=kitty


# Theme

# qt
export QT_QPA_PLATFORMTHEME=qt6ct
# export QT_STYLE_OVERRIDE=kvantum-dark
